name: finlog
description: "A new expense tracker"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.2
  cached_network_image: ^3.3.1

  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.7

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

  # Utils
  dartz: ^0.10.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting and Analysis
  flutter_lints: ^5.0.0
  
  # Testing
  bloc_test: ^9.1.6
  mockito: ^5.4.4
  build_runner: ^2.4.8


flutter:

  uses-material-design: true